name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    name: Set up Python 3.7
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          activate-environment: donkey
          environment-file: install/envs/pc.yml
          auto-activate-base: false
          channels: defaults, conda-forge
      - run: |
          conda info
          conda list



