name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda init bash
    - name: Install dependencies
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda config --append channels conda-forge
        conda update -q conda
        # Useful for debugging any issues with conda
        conda info -a
        conda env create -f install/envs/pc.yml
        conda init bash
        conda activate donkey
        pip install -e .
        conda env export > environment.yml
        cat environment.yml
